#!/usr/bin/env python3
import argparse
import json
import os
import random
import sys

import requests

ASS_HEADER = """[Script Info]
; Script generated by IanSung
Title: bahaDanmu
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 1920
PlayResY: 1080
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Roll,Microsoft JhengHei,50,&H4CFFFFFF,&H000000FF,&H4C000000,&HFF000000,-1,0,0,0,100,100,0,0,1,2,1,7,0,0,0,1
Style: Top,Microsoft JhengHei,50,&H4CFFFFFF,&H000000FF,&H4C000000,&HFF000000,-1,0,0,0,100,100,0,0,1,2,1,8,0,0,0,1
Style: Bottom,Microsoft JhengHei,50,&H4CFFFFFF,&H000000FF,&H4C000000,&HFF000000,-1,0,0,0,100,100,0,0,1,2,1,2,0,0,200,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""


def to_bgr(hex_rgb):
    return f"{hex_rgb[4:6]}{hex_rgb[2:4]}{hex_rgb[0:2]}"


def ts_format(dsec):
    sec = int(dsec / 10)
    cs = dsec % 10
    m, s = divmod(sec, 60)
    h, m = divmod(m, 60)
    return f"{h:d}:{m:02d}:{s:02d}.{cs:d}0"


def parse_time(tstr):
    parts = [int(x) for x in tstr.split(":")]
    if len(parts) == 2:
        return parts[0] * 600 + parts[1] * 10
    if len(parts) == 3:
        return parts[0] * 36000 + parts[1] * 600 + parts[2] * 10
    raise ValueError(f"Invalid time format: {tstr}")


def download(sn, output_path, jsonl=False, start_range=None):
    headers = {
        "Content-Type": "application/x-www-form-urlencoded;charset=utf-8",
        "origin": "https://ani.gamer.com.tw",
        "authority": "ani.gamer.com.tw",
        "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    }
    r = requests.post(
        "https://ani.gamer.com.tw/ajax/danmuGet.php",
        data={"sn": str(sn)},
        headers=headers,
    )
    if r.status_code != 200:
        print(f"彈幕下載失敗: status_code={r.status_code}", file=sys.stderr)
        sys.exit(1)

    items = json.loads(r.text)

    if start_range:
        start_dsec, end_dsec = start_range
        items = [it for it in items if start_dsec <= it["time"] <= end_dsec]

    if jsonl:
        with open(output_path, "w", encoding="utf-8") as f:
            for item in items:
                record = {"start": ts_format(item["time"]), "text": item["text"]}
                f.write(json.dumps(record, ensure_ascii=False) + "\n")
        print(f"JSONL 已儲存: {output_path}")
        return

    roll_channel = []
    roll_time = []

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(ASS_HEADER)

        for item in items:
            text = item["text"]
            t = item["time"]
            color = item["color"][1:]
            pos = item["position"]

            start_str = ts_format(t)
            sec = int(t / 10)

            if pos == 0:
                height = 0
                end_sec = 0
                for i in range(len(roll_channel)):
                    if roll_channel[i] <= t:
                        height = i * 54 + 27
                        roll_channel[i] = t + (len(text) * roll_time[i]) / 8 + 1
                        end_sec = sec + roll_time[i]
                        break
                if height == 0:
                    roll_channel.append(0)
                    roll_time.append(random.randint(10, 14))
                    roll_channel[-1] = t + (len(text) * roll_time[-1]) / 8 + 1
                    height = len(roll_channel) * 54 - 27
                    end_sec = sec + roll_time[-1]

                end_m, end_s = divmod(end_sec, 60)
                end_h, end_m = divmod(end_m, 60)
                end_str = f"{end_h:d}:{end_m:02d}:{end_s:02d}.{t % 10:d}0"
                style = f"Roll,,0,0,0,,{{\\move(1920,{height},-1000,{height})\\1c&H4C{to_bgr(color)}}}"
            elif pos == 1:
                end_sec = sec + 5
                end_m, end_s = divmod(end_sec, 60)
                end_h, end_m = divmod(end_m, 60)
                end_str = f"{end_h:d}:{end_m:02d}:{end_s:02d}.{t % 10:d}0"
                style = f"Top,,0,0,0,,{{\\1c&H4C{to_bgr(color)}}}"
            else:
                end_sec = sec + 5
                end_m, end_s = divmod(end_sec, 60)
                end_h, end_m = divmod(end_m, 60)
                end_str = f"{end_h:d}:{end_m:02d}:{end_s:02d}.{t % 10:d}0"
                style = f"Bottom,,0,0,0,,{{\\1c&H4C{to_bgr(color)}}}"

            f.write(f"Dialogue: 0,{start_str},{end_str},{style}{text}\n")

    print(f"字幕已儲存: {output_path}")


def main():
    parser = argparse.ArgumentParser(description="動畫瘋字幕下載工具")
    parser.add_argument("sn", type=int, help="影片 SN 碼")
    parser.add_argument("-o", "--output", help="輸出路徑 (預設: danmu_<sn>.ass)")
    parser.add_argument("--jsonl", action="store_true", help="輸出 JSONL 格式")
    parser.add_argument("--start-range", help="過濾開始時間範圍，格式: MM:SS~MM:SS")
    args = parser.parse_args()

    start_range = None
    if args.start_range:
        parts = args.start_range.split("~")
        if len(parts) != 2:
            print("錯誤: --start-range 格式應為 MM:SS~MM:SS", file=sys.stderr)
            sys.exit(1)
        start_range = (parse_time(parts[0]), parse_time(parts[1]))

    if args.jsonl and not args.output:
        args.output = f"danmu_{args.sn}.jsonl"

    output = args.output or f"danmu_{args.sn}.ass"
    download(args.sn, output, jsonl=args.jsonl, start_range=start_range)


if __name__ == "__main__":
    main()
